### ISSUE TITLE
NMEA2000_Teensyx.h:43:24: fatal error: RingBuffer.h: No such file or directory

### ISSUE THREAD

**Issue by hugorobi** [ttlappalainen/NMEA2000_Teensyx#2]
Hi,

I'm starting to move my project from Arduino Due to Teensy 4.1.

My first try with Teensy 4.1 board is to compile and run the example provided in the NMEA_Teensyx README.md file :

Unfortunatly, I got this message when compiling :

NMEA2000_Teensyx.h:43:24: fatal error: RingBuffer.h: No such file or directory

I've tried to install "RingBuffer" library, but the header file is not the same (RingBuf.h), and if I rename it as RingBuffer.h, I got many other errors.

Can someone help ?

**Comment by ttlappalainen** [comment]
You have not loaded latest version of NMEA2000 library.

**Comment by hugorobi** [comment]
🙄 Nice... Of course, new library need other to be updated.

Fixed !

Nice update last few months !

Great work !

Thank you.
