### ISSUE TITLE
need to modify  NMEA2000_CAN.h in order to get tNMEA2000_Teensyx NMEA2000; to work?

### ISSUE THREAD

**Issue by virtuvas** [ttlappalainen/NMEA2000_Teensyx#4]
hello Timo,

long time haven't played with anything...
Updated all libs and currently recompiling all my teensies. Most are 3.5 and there's a 3.6 in the mix. haven't used the 4.1 yet, but thought I'd try your suggestion to upgrade the 3.5 and 3.6 code to run on the teensyx lib.
Seems that I have to edit the NMEA2000_CAN.h lib to get it load the new teensyx lib.
I see that in NMEA2000_CAN.h you select which lib to use based on processor (line 200) and by default mine wants to use the teensy lib not the teensyx.
Is there a definition line or something to use and swap easily from one to another, instead of editing the lib itself??

At the moment my code starts with:

```
#include <Arduino.h>
#include <NMEA2000_CAN.h>

#include <N2kMsg.h>
#include <NMEA2000.h>

#include <N2kMessages.h>
```

cheers
Vassilis

**Comment by virtuvas** [comment]
I mean replacing:

```
USE_N2K_TEENSY_CAN
```
with 

```
USE_N2K_TEENSYX_CAN
```

in NMEA2000_CAN.h  lines 206 and 209 does the trick but not quite elegant!

**Comment by ttlappalainen** [comment]
Use

```
#include <Arduino.h>
#define USE_NMEA2000_TEENSYX_FOR_TEENSY_3X
#include <NMEA2000_CAN.h>

```
I have been thinking to change NMEA2000_Teensyx as default for all, but it brakes a bit compatibility. NMEA2000_Teensyx is more reliable according to my tests.

**Comment by virtuvas** [comment]
thanks Timo,

maybe worth adding this comment on the USAGE section of the README!

closing!

**Comment by ttlappalainen** [comment]
What section you mean? It is on the NMEA2000_CAN.h line 106
    #define USE_NMEA2000_TEENSYX_FOR_TEENSY_3X // Force NMEA2000_TEENSYX also for Teensy 3.x boards

And also on document https://ttlappalainen.github.io/NMEA2000/pg_lib_ref.html#autotoc_md21

**Comment by virtuvas** [comment]
> 
> And also on document https://ttlappalainen.github.io/NMEA2000/pg_lib_ref.html#autotoc_md21

apologies, 

have completely missed your work on documenting everything in github.io!
I was only downloading a zip of the lib and using it with whatever documentation/examples were included.
nice job!

thanks
V.

**Comment by ttlappalainen** [comment]
Actually thanks to document goes to Matthias Werner. He did last year really big job changing everything to Doxygen format and collected my comments to files. Now it is easier to improve document. I did some fixes and updates for documentation some weeks ago.

Me and Matthias are not native English, so there may be lot wrong terms, miss spelling (garaminowicz just fixed a lot). I'll be happy for fixes also to document.

**Comment by virtuvas** [comment]
thanks to all involved then!
not a native speaker either, will have time to work on my teensies mid March onwards, and will have a good look on the docs and report!

V.
